version: '3.9'

services:
  db:
    container_name: postgres-db
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  python-app:
    container_name: python-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - db_network
    env_file:
      - .env
    environment:
      - DB_HOST=postgres-db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["gunicorn", "--workers", "3", "--bind", "0.0.0.0:8000", "wsgi:app", "--reload"]

volumes:
  postgres_data:

networks:
  db_network:
